language: cpp

sudo: required

dist: xenial

install:
 - sudo apt-get update -y
 - sudo apt-get install -y cmake libboost-all-dev ninja-build

script:
 - mkdir -p build
 - cd build
 - cmake -G Ninja ../
 - ninja -v
 - ctest 
