language: cpp

sudo: required

dist: trusty

install:
 - sudo apt update -y
 - sudo apt upgrade -y
 - sudo apt install -y cmake libboost-all-dev

script:
 - mkdir -p build
 - cd build
 - cmake ../
 - make
 - ctest -V
