language: cpp

matrix:
  include:
   - os: linux
     dist: xenial
   - os: osx
     osx_image: xcode10.2

sudo: required

before_install:
 - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update          ; fi
 - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install ninja          ; fi
 - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install boost || true ; fi
 - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get update -y ; fi
 - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install -y cmake libboost-all-dev ninja-build ; fi

script:
 - mkdir -p build
 - cd build
 - cmake -G Ninja ../
 - ninja -v
 - ctest 
